# Generated by Django 3.0 on 2019-12-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191221_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcategory',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
