# Generated by Django 3.0 on 2019-12-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_category_available'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpCategory',
            new_name='UpCategoryList',
        ),
    ]
