# Generated by Django 3.0 on 2019-12-22 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20191222_1751'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpCategoryList',
            new_name='UpCategory',
        ),
    ]
